/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaodienUI;

import DTo.DiaDiemVuiChoi;
import DTo.NhanVien;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.codec.language.DaitchMokotoffSoundex;

/**
 *
 * @author Thanh Tran
 */
public class QlyDiaDiemVuiChoi extends javax.swing.JPanel {
    ArrayList<DiaDiemVuiChoi> danhSachdd = new ArrayList<DiaDiemVuiChoi>();
    /**
     * Creates new form QlyDiaDiemVuiChoi
     */
    public QlyDiaDiemVuiChoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbxDiaDiemTour = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDiaDiem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaDiaDiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnExport = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        setBackground(new java.awt.Color(167, 169, 177));

        jPanel1.setBackground(new java.awt.Color(167, 169, 177));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 0, 6));
        jLabel2.setText("                                     Hệ Thống Quản Lý Các Địa Điểm Vui Chơi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel1)
                .addContainerGap(579, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(167, 169, 177));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 0, 6));
        jLabel3.setText(" Địa Điểm Tour");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbxDiaDiemTour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Địa Điểm Tour", " " }));
        cbxDiaDiemTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaDiemTourActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 0, 6));
        jLabel4.setText("  Tên Địa Điểm");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtDiaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaDiemActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 0, 6));
        jLabel5.setText("   Mã Địa Điểm");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtMaDiaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDiaDiemActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(21, 110, 71));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(21, 110, 71));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(21, 110, 71));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(21, 110, 71));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        btnExport.setBackground(new java.awt.Color(21, 110, 71));
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxDiaDiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnTimKiem)
                        .addGap(78, 78, 78)
                        .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxDiaDiemTour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiaDiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport))
                .addGap(14, 14, 14))
        );

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Địa Điểm Tour", "Điểm Vui Chơi", "Mã Địa Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator5)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDiaDiemTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaDiemTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiaDiemTourActionPerformed

    private void txtDiaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaDiemActionPerformed

    private void txtMaDiaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDiaDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDiaDiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       
        
        String diadiemTour = cbxDiaDiemTour.getSelectedItem().toString();
        String diadiem = txtDiaDiem.getText();
        String madiadiem = txtMaDiaDiem.getText();


        if (diadiemTour.equals("")) {
            JOptionPane.showMessageDialog(null, "Nhập Đầy Đủ Thông Tin");
        } else if (diadiem.equals("")) {
            JOptionPane.showMessageDialog(null, "Nhập Đầy Đủ Thông Tin");
        } else if (madiadiem.equals("")) {
            JOptionPane.showMessageDialog(null, "Nhập Đầy Đủ Thông Tin");
     
        } else {
            // Tạo đối tượng DTO
            DiaDiemVuiChoi nv = new DiaDiemVuiChoi(diadiemTour,diadiem,madiadiem);

            // Thêm đối tượng vào danh sách
            danhSachdd.add(nv);
         
            // Tạo đối tượng DefaultTableModel
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            // thêm đối tượng KhachHang vào model
            model.addRow(new Object[]{nv.getDiaDiemTour(), nv.getTenDiaDiem(), nv.getMaDiaDiem()});

// cập nhật lại model cho JTable
            jTable1.setModel(model);

// thông báo thành công
            JOptionPane.showMessageDialog(null, "Thêm Địa điểm vui chơi Thành Công");
            
            txtDiaDiem.setText("");
            txtMaDiaDiem.setText("");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       
        int selectedRow = jTable1.getSelectedRow();

// nếu không có hàng nào được chọn, thông báo lỗi và kết thúc
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Một Hàng Để Xóa");
            return;
        }

// lấy ra model của JTable hiện tại
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// lấy mã khách hàng của hàng được chọn
        String maNV = (String) model.getValueAt(selectedRow, 2);

// tìm khách hàng trong danh sách dựa vào mã
        DiaDiemVuiChoi nhanVienCanXoa = null;
        for (DiaDiemVuiChoi nv : danhSachdd) {
            if (nv.getMaDiaDiem().equals(maNV)) {
                nhanVienCanXoa = nv;
                break;
            }
        }

// nếu không tìm thấy khách hàng, thông báo lỗi và kết thúc
        if (nhanVienCanXoa == null) {
            JOptionPane.showMessageDialog(null, "Địa điểm Không Tồn Tại");
            return;
        }

// xóa khách hàng khỏi danh sách
        danhSachdd.remove(nhanVienCanXoa);
        
// xóa hàng được chọn trong model
        model.removeRow(selectedRow);

// cập nhật lại model cho JTable
        jTable1.setModel(model);

// thông báo thành công
        JOptionPane.showMessageDialog(null, "Xóa địa điểm vui chơi Thành Công");

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // lấy chỉ số hàng được chọn trong JTable
        int selectedRow = jTable1.getSelectedRow();

// nếu không có hàng nào được chọn, thông báo lỗi và kết thúc
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Một Hàng Để Sửa");
            return;
        }

// lấy ra model của JTable hiện tại
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// lấy mã khách hàng của hàng được chọn
        String maNV = (String) model.getValueAt(selectedRow, 2);
        String oldNV = maNV;
// tìm khách hàng trong danh sách dựa vào mã
        DiaDiemVuiChoi nhanVienCanSua = null;
        for (DiaDiemVuiChoi nv : danhSachdd) {
            if (nv.getMaDiaDiem().equals(maNV)) {
                nhanVienCanSua = nv;
                break;
            }
        }

// nếu không tìm thấy khách hàng, thông báo lỗi và kết thúc
        if (nhanVienCanSua == null) {
            JOptionPane.showMessageDialog(null, "Đại điểm Không Tồn Tại");
            return;
        }

// hiển thị form sửa thông tin khách hàng
     
// thêm ComboBox để chọn loại nhân viên
        JComboBox<String> cbxDiaDiemTour = new JComboBox<>();
        cbxDiaDiemTour.addItem("Nhân Viên Bán Hàng");
        cbxDiaDiemTour.addItem("Quản Lý Kho");
        cbxDiaDiemTour.addItem("Nhân Viên Văn Phòng");
        cbxDiaDiemTour.setSelectedItem(nhanVienCanSua.getDiaDiemTour());
        JOptionPane.showMessageDialog(null, cbxDiaDiemTour, "Chọn địa điểm Tour", JOptionPane.QUESTION_MESSAGE);

        String diaDiemTour = (String) cbxDiaDiemTour.getSelectedItem();
// thêm ComboBox để chọn chức vụ
      String maNVNew = JOptionPane.showInputDialog(null, "Nhập mã địa điểm", maNV);
      String diadiem = JOptionPane.showInputDialog(null, "Nhập diadiem", nhanVienCanSua.getTenDiaDiem());
      

// cập nhật thông tin khách hàng
        nhanVienCanSua.setDiaDiemTour(diaDiemTour);
        nhanVienCanSua.setTenDiaDiem(diadiem);
        nhanVienCanSua.setMaDiaDiem(maNV);


// cập nhật lại model cho JTable
        model.setValueAt(diaDiemTour, selectedRow, 0);
        model.setValueAt(diadiem, selectedRow, 1);
        model.setValueAt(maNV, selectedRow, 2);
      


// thông báo thành công
        JOptionPane.showMessageDialog(null, "Sửa Thông Tin Nhân Viên Thành Công");

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maNVCanTim = txtMaDiaDiem.getText();

        // Tạo một danh sách để lưu khách hàng tìm được
        ArrayList<DiaDiemVuiChoi> ketQuaTimKiem = new ArrayList<>();

        // Lặp qua danh sách khách hàng hiện tại để tìm kiếm
        for (DiaDiemVuiChoi nv : danhSachdd) {
            if (nv.getMaDiaDiem().toLowerCase().contains(maNVCanTim.toLowerCase())) {
                ketQuaTimKiem.add(nv);
            } else {
                JOptionPane.showMessageDialog(null, "Kết Quả Không Tìm Thấy");
                return;
            }
        }

        // Tạo một model mới để hiển thị kết quả tìm kiếm trên JTable
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Địa điểm Tour");
        model.addColumn("Điểm vui chơi");
        model.addColumn("Mã địa điểm");
       

        // Thêm các khách hàng tìm được vào model
        for (DiaDiemVuiChoi nv : ketQuaTimKiem) {
            model.addRow(new Object[]{nv.getDiaDiemTour(), nv.getTenDiaDiem(), nv.getMaDiaDiem()});
        }

        // Cập nhật lại model cho JTable
        jTable1.setModel(model);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxDiaDiemTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiaDiem;
    private javax.swing.JTextField txtMaDiaDiem;
    // End of variables declaration//GEN-END:variables
}
