/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaodienUI;

import DTo.KhachSan;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DTo.KhuyenMai;
import DTo.Tour;
import KetnoiSQL_DAL.config;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
/**
 *
 * @author Thanh Tran
 */
public class QlyKhuyenMai extends javax.swing.JPanel {

    config con = new config();
    DefaultTableModel model = new DefaultTableModel();
    ArrayList<KhuyenMai> danhSachKM = new ArrayList<>();
    /**
     * Creates new form QlyKhuyenMai
     */
    public QlyKhuyenMai() {
        initComponents();
        try {
            danhSachKM = con.layDL_KhuyenMai();
        } catch (SQLException ex) {
            Logger.getLogger(QlyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (KhuyenMai km : danhSachKM) {
            model.addRow(new Object[]{km.getTenkm(),km.getMakm(), km.getNgaykm(), km.getHansudung(), km.getTiengiam()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtTenKhuyenMai = new javax.swing.JTextField();
        txtMaKhuyenMai = new javax.swing.JTextField();
        cbxNgayKhuyenMai = new javax.swing.JComboBox<>();
        cbxThangKhuyenMai = new javax.swing.JComboBox<>();
        cbxNamKhuyenMai = new javax.swing.JComboBox<>();
        cbxNgayHanSuDung = new javax.swing.JComboBox<>();
        cbxThangHanSuDung = new javax.swing.JComboBox<>();
        cbxNamHanSuDung = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTienGiam = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(167, 169, 177));

        jPanel1.setBackground(new java.awt.Color(167, 169, 177));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 0, 6));
        jLabel1.setText("                                              Hệ Thống Quản Lý Khuyến Mãi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(167, 169, 177));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTenKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhuyenMaiActionPerformed(evt);
            }
        });

        txtMaKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKhuyenMaiActionPerformed(evt);
            }
        });

        cbxNgayKhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        cbxNgayKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNgayKhuyenMaiActionPerformed(evt);
            }
        });

        cbxThangKhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxThangKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThangKhuyenMaiActionPerformed(evt);
            }
        });

        cbxNamKhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2023" }));
        cbxNamKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNamKhuyenMaiActionPerformed(evt);
            }
        });

        cbxNgayHanSuDung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        cbxNgayHanSuDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNgayHanSuDungActionPerformed(evt);
            }
        });

        cbxThangHanSuDung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxThangHanSuDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThangHanSuDungActionPerformed(evt);
            }
        });

        cbxNamHanSuDung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2023" }));
        cbxNamHanSuDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNamHanSuDungActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnThem.setBackground(new java.awt.Color(21, 110, 71));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(21, 110, 71));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(21, 110, 71));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(21, 110, 71));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 0, 6));
        jLabel2.setText("  Tên Khuyến Mãi");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 0, 6));
        jLabel3.setText(" Mã Khuyến Mãi");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 0, 6));
        jLabel4.setText("  Ngày Khuyến Mãi");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 0, 6));
        jLabel5.setText("      Hạn Sử Dụng");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );

        txtTienGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienGiamActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 0, 6));
        jLabel6.setText("    Tiền Giảm");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxNgayKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxNgayHanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbxThangHanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxNamHanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbxThangKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(cbxNamKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtTienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(230, 230, 230))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnTimKiem)
                        .addGap(45, 45, 45)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaKhuyenMai)
                    .addComponent(txtTenKhuyenMai))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxThangKhuyenMai)
                        .addComponent(cbxNgayKhuyenMai))
                    .addComponent(cbxNamKhuyenMai))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxThangHanSuDung)
                        .addComponent(cbxNgayHanSuDung))
                    .addComponent(cbxNamHanSuDung))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTienGiam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnTimKiem))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Khuyến Mãi", "Mã Khuyến Mãi", "Ngày Khuyến Mãi", "Hạn Sử Dụng", "Tiền Giảm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhuyenMaiActionPerformed

    private void txtMaKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKhuyenMaiActionPerformed

    private void cbxNgayKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNgayKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNgayKhuyenMaiActionPerformed

    private void cbxThangKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThangKhuyenMaiActionPerformed
        // TODO add your handling code here:
        String thang = cbxThangKhuyenMai.getSelectedItem().toString();
int day = 0;

//Những tháng 1,3,5,7,8,10,12 thì có 31 ngày trong năm 2023
if(thang.equals("1")){
    cbxNgayKhuyenMai.removeAllItems();
    cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("3")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("5")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("7")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("8")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("10")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("12")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}

//Những tháng 4,6,9,11 thì có 30 ngày trong năm 2023
if(thang.equals("4")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 31 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("6")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 31 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("9")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 31 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("11")){
    cbxNgayKhuyenMai.removeAllItems();
cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 31 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}

//Còn lại là tháng 2 có 28 ngày trong năm 2023
if(thang.equals("2")){
    cbxNgayKhuyenMai.removeAllItems();
    cbxNgayKhuyenMai.addItem("Ngày");
    for(int i = 1 ; i < 29 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayKhuyenMai.addItem(Day);
        Day = "";
    }
}

    }//GEN-LAST:event_cbxThangKhuyenMaiActionPerformed

    private void cbxNamKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNamKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNamKhuyenMaiActionPerformed

    private void cbxNgayHanSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNgayHanSuDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNgayHanSuDungActionPerformed

    private void cbxThangHanSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThangHanSuDungActionPerformed
        // TODO add your handling code here:
        String thang = cbxThangHanSuDung.getSelectedItem().toString();
int day = 0;

//Những tháng 1,3,5,7,8,10,12 thì có 31 ngày trong năm 2023
if(thang.equals("1")){
    cbxNgayHanSuDung.removeAllItems();
    cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("3")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("5")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("7")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("8")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("10")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("12")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 32 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}

//Những tháng 4,6,9,11 thì có 30 ngày trong năm 2023
if(thang.equals("4")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 31 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("6")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 31 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("9")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 31 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
else if(thang.equals("11")){
    cbxNgayHanSuDung.removeAllItems();
cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 31 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}

//Còn lại là tháng 2 có 28 ngày trong năm 2023
if(thang.equals("2")){
    cbxNgayHanSuDung.removeAllItems();
    cbxNgayHanSuDung.addItem("Ngày");
    for(int i = 1 ; i < 29 ; i++){
        day = i;
        String Day = Integer.toString(day);
        cbxNgayHanSuDung.addItem(Day);
        Day = "";
    }
}
    }//GEN-LAST:event_cbxThangHanSuDungActionPerformed

    private void cbxNamHanSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNamHanSuDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNamHanSuDungActionPerformed

    private void txtTienGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienGiamActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       try {
            danhSachKM = con.layDL_KhuyenMai();
        } catch (SQLException ex) {
            Logger.getLogger(QlyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
        String tenKM = txtTenKhuyenMai.getText();
        String maKM = txtMaKhuyenMai.getText();
        long tienGiam = Long.parseLong(txtTienGiam.getText());
        int ngayKM = Integer.parseInt(cbxNgayKhuyenMai.getSelectedItem().toString());
        int thangKM = Integer.parseInt(cbxThangKhuyenMai.getSelectedItem().toString());
        int namKM = Integer.parseInt(cbxNamKhuyenMai.getSelectedItem().toString());
        int ngayHSD = Integer.parseInt(cbxNgayHanSuDung.getSelectedItem().toString());
        int thangHSD = Integer.parseInt(cbxThangHanSuDung.getSelectedItem().toString());
        int namHSD = Integer.parseInt(cbxNamHanSuDung.getSelectedItem().toString());
        
        Calendar calendar = Calendar.getInstance();
        calendar.set(namKM,thangKM - 1,ngayKM);
        Date ngayKMDate = calendar.getTime();
        calendar.set(namHSD,thangHSD - 1,ngayHSD);
        Date hanSDDate = calendar.getTime();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String ngayKMString = dateFormat.format(ngayKMDate);
        String hanSDString = dateFormat.format(hanSDDate);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
        KhuyenMai km = new KhuyenMai(tenKM,maKM,ngayKM,ngayHSD,tienGiam);
        danhSachKM.add(km);
        con.UpdateSQL_KhuyenMai(km, 2, "null");
        model.addRow(new Object[]{km.getTenkm(),km.getMakm(),ngayKMString, hanSDString, km.getTiengiam()});
        
        jTable1.setModel(model);
        
                   JOptionPane.showMessageDialog(null,"Thêm Khuyến Mãi Thành Công");
                   
        txtTenKhuyenMai.setText("");
                txtMaKhuyenMai.setText("");
        txtTienGiam.setText("");
        
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null,"Vui Lòng Nhập Đầy Đủ Thông Tin Và Kiểm Tra Lại");
       }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         int selectedRow = jTable1.getSelectedRow();
        try {
            danhSachKM = con.layDL_KhuyenMai();
        } catch (SQLException ex) {
            Logger.getLogger(QlyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn 1 Hàng Để Xóa");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        String maKM = (String) model.getValueAt(selectedRow, 1);
        
        KhuyenMai khuyenMaiCanXoa = null;
        for(KhuyenMai km : danhSachKM){
            if(km.getMakm().equals(maKM)){
                khuyenMaiCanXoa = km;
                break;
            }
        }
        con.UpdateSQL_KhuyenMai(khuyenMaiCanXoa, 2, "null");
        
        if(khuyenMaiCanXoa == null){
            JOptionPane.showMessageDialog(null,"Khuyến Mãi Không Tồn Tại");
        }
        
        danhSachKM.remove(khuyenMaiCanXoa);
        model.removeRow(selectedRow);
        
        jTable1.setModel(model);
        
        JOptionPane.showMessageDialog(null,"Xóa Khuyến Mãi Thành Công");
       
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // lấy chỉ số hàng được chọn trong JTable
        int selectedRow = jTable1.getSelectedRow();
try {
            danhSachKM = con.layDL_KhuyenMai();
        } catch (SQLException ex) {
            Logger.getLogger(QlyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
// nếu không có hàng nào được chọn, thông báo lỗi và kết thúc
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Một Hàng Để Sửa");
            return;
        }

// lấy ra model của JTable hiện tại
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// lấy mã khách hàng của hàng được chọn
        String maNV = (String) model.getValueAt(selectedRow, 1);
        String old = maNV;
// tìm khách hàng trong danh sách dựa vào mã
        KhuyenMai tourCanSua = null;
        for (KhuyenMai nv : danhSachKM) {
            if (nv.getMakm().equals(maNV)) {
                tourCanSua = nv;
                break;
            }
        }

// nếu không tìm thấy khách hàng, thông báo lỗi và kết thúc
        if (tourCanSua == null) {
            JOptionPane.showMessageDialog(null, "Tour Không Tồn Tại");
            return;
        }

// hiển thị form sửa thông tin khách hàng
        String tenKM = JOptionPane.showInputDialog(null, "Nhập tên khuyến mãi", tourCanSua.getTenkm());
        String maKm = JOptionPane.showInputDialog(null, "Nhập mã khuyến mãi", maNV);
        long soTienGiam = Long.parseLong(JOptionPane.showInputDialog(null, "Nhập số tiền giảm", String.valueOf(tourCanSua.getTiengiam())));

// thêm ComboBox để chọn loại nhân viên
        JComboBox<String> cbxnamDi = new JComboBox<>();
        cbxnamDi.addItem("2023");

        cbxnamDi.setSelectedItem(tourCanSua.getNgaykm());

        JOptionPane.showMessageDialog(null, cbxnamDi, "Chọn năm KM", JOptionPane.QUESTION_MESSAGE);
        String namDiString = (String) cbxnamDi.getSelectedItem();
        int namDi = Integer.parseInt(namDiString);

        JComboBox<String> cbxThangDi = new JComboBox<>();
        int day = 0;
        for (int i = 1; i < 13; i++) {
            day = i;
            String Day = Integer.toString(day);
            cbxThangDi.addItem(Day);
            Day = "";
        }
        cbxThangDi.setSelectedItem(tourCanSua.getNgaykm());
        JOptionPane.showMessageDialog(null, cbxThangDi, "Chọn Tháng khuyến mãi", JOptionPane.QUESTION_MESSAGE);
        String TDiString = (String) cbxThangDi.getSelectedItem();
        int ThangDi = Integer.parseInt(TDiString);

        JComboBox<String> cbxNgayDi = new JComboBox<>();
        for (int i = 1; i < 32; i++) {
            String Day = Integer.toString(i);
            cbxNgayDi.addItem(Day);
            Day = "";
        }
        cbxNgayDi.setSelectedItem(tourCanSua.getNgaykm());
        JOptionPane.showMessageDialog(null, cbxNgayDi, "Chọn Ngày khuyến mãi", JOptionPane.QUESTION_MESSAGE);
        String ngaydi = (String) cbxNgayDi.getSelectedItem();
        int ngayDi = Integer.parseInt(ngaydi);

        JComboBox<String> cbxnamVe = new JComboBox<>();
        cbxnamVe.addItem("2023");

        cbxnamVe.setSelectedItem(tourCanSua.getHansudung());

        JOptionPane.showMessageDialog(null, cbxnamVe, "Chọn năm khuyến mãi", JOptionPane.QUESTION_MESSAGE);
        String namVeString = (String) cbxnamDi.getSelectedItem();
        int namVe = Integer.parseInt(namVeString);
        JComboBox<String> cbxThangVe = new JComboBox<>();
        for (int i = 1; i < 13; i++) {
            day = i;
            String Day = Integer.toString(day);
            cbxThangVe.addItem(Day);
            Day = "";
        }
        cbxThangVe.setSelectedItem(tourCanSua.getHansudung());
        JOptionPane.showMessageDialog(null, cbxThangVe, "Chọn Tháng khuyến mãi", JOptionPane.QUESTION_MESSAGE);
        String TVeString = (String) cbxThangVe.getSelectedItem();
        int ThangVe = Integer.parseInt(TVeString);

        JComboBox<String> cbxNgayVe = new JComboBox<>();
        for (int i = 1; i < 32; i++) {
            String Day = Integer.toString(i);
            cbxNgayVe.addItem(Day);
            Day = "";
        }
        cbxNgayVe.setSelectedItem(tourCanSua.getHansudung());
        JOptionPane.showMessageDialog(null, cbxNgayVe, "Chọn Ngày khuyến mãi", JOptionPane.QUESTION_MESSAGE);
        String ngayve = (String) cbxNgayVe.getSelectedItem();
        int ngayVe = Integer.parseInt(ngayve);

       

        Calendar calendar = Calendar.getInstance();
        calendar.set(namDi, ThangDi - 1, ngayDi);
        Date ngayDiDate = calendar.getTime();
        calendar.set(namVe, ThangVe - 1, ngayVe);
        Date ngayVeDate = calendar.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String ngayDiString = dateFormat.format(ngayDiDate);
        String ngayVeString = dateFormat.format(ngayVeDate);

// cập nhật thông tin khách hàng
        tourCanSua.setTenkm(tenKM);
        tourCanSua.setMakm(maKm);
     
        
        tourCanSua.setNgaykm(ngayDi);
        tourCanSua.setHansudung(ngayVe);
    
        tourCanSua.setTiengiam(soTienGiam);

// cập nhật lại model cho JTable
        model.setValueAt(tenKM, selectedRow, 0);
        model.setValueAt(maKm, selectedRow, 1);
        model.setValueAt(ngayDiString, selectedRow, 2);
        model.setValueAt(ngayVeString, selectedRow, 3);
        model.setValueAt(soTienGiam, selectedRow, 4);
       
        con.UpdateSQL_KhuyenMai(tourCanSua, 3, old);
// thông báo thành công
        JOptionPane.showMessageDialog(null, "Sửa Thông Tin Khuyến mãi Thành Công");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
       String tuKhoa = txtMaKhuyenMai.getText().toLowerCase().trim();
        config con = new config();
        
        try {
            danhSachKM = con.layDL_KhuyenMai();
        } catch (SQLException ex) {
            Logger.getLogger(QlyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (tuKhoa.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khóa tìm kiếm");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        /*for (int i = 0; i < danhSachTour.size(); i++) {
        model.removeRow(i);
        }*/
        for (int i = 0; i < danhSachKM.size(); i++) {
            KhuyenMai tour = danhSachKM.get(i);
            if (tour.getTenkm().toLowerCase().contains(tuKhoa)
                    || tour.getMakm().toLowerCase().contains(tuKhoa)) {
                
               
                    if (tuKhoa.equals(danhSachKM.get(i).getMakm())) {
                        model.addRow(new Object[]{danhSachKM.get(i).getTenkm(), danhSachKM.get(i).getMakm(), danhSachKM.get(i).getNgaykm(), danhSachKM.get(i).getHansudung(), danhSachKM.get(i).getTiengiam()});
                    }
                

            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxNamHanSuDung;
    private javax.swing.JComboBox<String> cbxNamKhuyenMai;
    private javax.swing.JComboBox<String> cbxNgayHanSuDung;
    private javax.swing.JComboBox<String> cbxNgayKhuyenMai;
    private javax.swing.JComboBox<String> cbxThangHanSuDung;
    private javax.swing.JComboBox<String> cbxThangKhuyenMai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMaKhuyenMai;
    private javax.swing.JTextField txtTenKhuyenMai;
    private javax.swing.JTextField txtTienGiam;
    // End of variables declaration//GEN-END:variables
}
