/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaodienUI;

import DTo.DiaDiemVuiChoi;
import DTo.Tour;
import KetnoiSQL_DAL.config;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
/**
 *
 * @author Thanh Tran
 */
public class QlyTourDuLich extends javax.swing.JPanel {

    ArrayList<Tour> danhSachTour = new ArrayList<Tour>();
    config con = new config();
    /**
     * Creates new form QlyVeTour
     */
    public QlyTourDuLich() {
        initComponents();
        
        try {
            danhSachTour = con.layDL_Tour();
        } catch (SQLException ex) {
            Logger.getLogger(QlyTourDuLich.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (Tour nv : danhSachTour) {            
        model.addRow(new Object[]{nv.getTenTour(), nv.getMaTour(), nv.getLoaiTour(), nv.getTongsocho(), nv.getSochodu(), nv.getDiaDiemTour(), nv.getDiaDiemdi(), nv.getDiaDiemden(), nv.getSongaydi(), ngayDiString, ngayVeString, nv.getGiaTour()});
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTenTour = new javax.swing.JTextField();
        txtMaTour = new javax.swing.JTextField();
        txtTongSoCho = new javax.swing.JTextField();
        txtSoChoDu = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtDiaDiemTour = new javax.swing.JTextField();
        txtDiaDiemDi = new javax.swing.JTextField();
        txtDiaDiemDen = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtSoNgayDi = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbxNgayDi = new javax.swing.JComboBox<>();
        cbxThangDi = new javax.swing.JComboBox<>();
        cbxNamDi = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbxNgayVe = new javax.swing.JComboBox<>();
        cbxThangVe = new javax.swing.JComboBox<>();
        cbxNamVe = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtGiaTour = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        cbxLoaiTour = new javax.swing.JComboBox<>();
        btnExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("jButton1");

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(167, 169, 177));

        jPanel1.setBackground(new java.awt.Color(167, 169, 177));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 0, 6));
        jLabel1.setText("                                             Hệ Thống Quản Lý Tour Du Lịch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(167, 169, 177));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 0, 6));
        jLabel2.setText("     Tên Tour");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 0, 6));
        jLabel3.setText("     Mã Tour");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 0, 6));
        jLabel4.setText("     Loại Tour");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 0, 6));
        jLabel5.setText("  Tổng Số Chỗ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 0, 6));
        jLabel6.setText("    Số Chỗ Dư");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(169, 0, 6));
        jLabel10.setText("   Địa Điểm Tour");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(169, 0, 6));
        jLabel8.setText("    Địa Điểm Đến");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 0, 6));
        jLabel7.setText("     Địa Điểm Đi");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        txtDiaDiemDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaDiemDenActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(169, 0, 6));
        jLabel9.setText("      Số Ngày Đi");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtSoNgayDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNgayDiActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(169, 0, 6));
        jLabel11.setText("       Ngày ĐI");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        cbxNgayDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        cbxNgayDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNgayDiActionPerformed(evt);
            }
        });

        cbxThangDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        cbxThangDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThangDiActionPerformed(evt);
            }
        });

        cbxNamDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2023", " " }));
        cbxNamDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNamDiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(169, 0, 6));
        jLabel12.setText("       Ngày Về");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        cbxNgayVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        cbxNgayVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNgayVeActionPerformed(evt);
            }
        });

        cbxThangVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxThangVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxThangVeActionPerformed(evt);
            }
        });

        cbxNamVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2023", " " }));
        cbxNamVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNamVeActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(169, 0, 6));
        jLabel13.setText("       Giá Tour");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        btnThem.setBackground(new java.awt.Color(21, 110, 71));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setBorderPainted(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(21, 110, 71));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(21, 110, 71));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setBorderPainted(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(21, 110, 71));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setBorderPainted(false);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        cbxLoaiTour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại Tour", "Nhân Viên Bán Hàng", "Quản Lý Kho", "Nhân Viên Văn Phòng", " " }));
        cbxLoaiTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiTourActionPerformed(evt);
            }
        });

        btnExport.setBackground(new java.awt.Color(21, 110, 71));
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(btnTimKiem)
                                .addGap(65, 65, 65)
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxLoaiTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongSoCho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoChoDu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiaDiemDen, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiaDiemDi, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiaDiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(132, 132, 132))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNgayDi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNgayVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxThangDi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxNamDi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxThangVe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxNamVe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenTour)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaTour)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxLoaiTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTongSoCho)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoChoDu)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiaDiemTour, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDiaDiemDi))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDiaDiemDen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoNgayDi)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxThangDi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxNamDi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxNgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxThangVe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxNamVe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnExport)
                    .addComponent(btnTimKiem)
                    .addComponent(btnSua))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Tour", "Mã Tour", "Loại Tour", "Tổng Số Chỗ", "Số Chỗ Dư", "Địa Điểm Tour", "Địa Điểm Đi", "Địa Điểm Đến", "Số Ngày Đi", "Ngày Đi", "Ngày Về", "Giá Tour"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoNgayDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNgayDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNgayDiActionPerformed

    private void cbxNgayDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNgayDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNgayDiActionPerformed

    private void cbxThangDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThangDiActionPerformed
        String thang = cbxThangDi.getSelectedItem().toString();
        int day = 0;

//Những tháng 1,3,5,7,8,10,12 thì có 31 ngày trong năm 2023
        if (thang.equals("1")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("3")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("5")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("7")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("8")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("10")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("12")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        }

//Những tháng 4,6,9,11 thì có 30 ngày trong năm 2023
        if (thang.equals("4")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("6")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("9")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("11")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        }

//Còn lại là tháng 2 có 28 ngày trong năm 2023
        if (thang.equals("2")) {
            cbxNgayDi.removeAllItems();
            cbxNgayDi.addItem("Ngày");
            for (int i = 1; i < 29; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayDi.addItem(Day);
                Day = "";
            }
        }

    }//GEN-LAST:event_cbxThangDiActionPerformed

    private void cbxNamDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNamDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNamDiActionPerformed

    private void cbxNgayVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNgayVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNgayVeActionPerformed

    private void cbxThangVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxThangVeActionPerformed
        // TODO add your handling code here:
        String thang = cbxThangVe.getSelectedItem().toString();
        int day = 0;

//Những tháng 1,3,5,7,8,10,12 thì có 31 ngày trong năm 2023
        if (thang.equals("1")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");
            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("3")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("5")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("7")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("8")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("10")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("12")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 32; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        }

//Những tháng 4,6,9,11 thì có 30 ngày trong năm 2023
        if (thang.equals("4")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("6")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("9")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        } else if (thang.equals("11")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 31; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        }

//Còn lại là tháng 2 có 28 ngày trong năm 2023
        if (thang.equals("2")) {
            cbxNgayVe.removeAllItems();
            cbxNgayVe.addItem("Ngày");

            for (int i = 1; i < 29; i++) {
                day = i;
                String Day = Integer.toString(day);
                cbxNgayVe.addItem(Day);
                Day = "";
            }
        }

    }//GEN-LAST:event_cbxThangVeActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // Lấy dữ liệu từ các trường nhập liệu trên GUI
        config con = new config();
        try {
            danhSachTour = con.layDL_Tour();
        } catch (SQLException ex) {
            Logger.getLogger(QlyTourDuLich.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            String tenTour = txtTenTour.getText();
            String maTour = txtMaTour.getText();
            String loaiTour = cbxLoaiTour.getSelectedItem().toString();
            int tongSoCho = Integer.parseInt(txtTongSoCho.getText());
            int soChoDu = Integer.parseInt(txtSoChoDu.getText());
            String diaDiemTour = txtDiaDiemTour.getText();
            String diaDiemDi = txtDiaDiemDi.getText();
            String diaDiemDen = txtDiaDiemDen.getText();
            int soNgayDi = Integer.parseInt(txtSoNgayDi.getText());

// Lấy ngày tháng năm từ các JComboBox
              int ngayDi = Integer.parseInt(cbxNgayDi.getSelectedItem().toString());
            int thangDi = Integer.parseInt(cbxThangDi.getSelectedItem().toString());
            int namDi = Integer.parseInt(cbxNamDi.getSelectedItem().toString());
            int ngayVe = Integer.parseInt(cbxNgayVe.getSelectedItem().toString());
            int thangVe = Integer.parseInt(cbxThangVe.getSelectedItem().toString());
            int namVe = Integer.parseInt(cbxNamVe.getSelectedItem().toString());

// Tạo đối tượng Date từ ngày tháng năm
            Calendar calendar = Calendar.getInstance();
            calendar.set(namDi , thangDi, ngayDi);
            Date ngayDiDate = calendar.getTime();

            calendar.set(namVe , thangVe, ngayVe);
            Date ngayVeDate = calendar.getTime();
         
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                String ngayDiString = dateFormat.format(ngayDiDate);
                String ngayVeString = dateFormat.format(ngayVeDate);
            long giaTour = Long.parseLong(txtGiaTour.getText());

// Tạo đối tượng DTO
            Tour nv = new Tour(tenTour, maTour, loaiTour, tongSoCho, soChoDu, diaDiemTour, diaDiemDi, diaDiemDen, soNgayDi, ngayDiDate, ngayVeDate, giaTour);

            // Thêm đối tượng vào danh sách
            danhSachTour.add(nv);
            con.UpdateSQL_Tour(nv, 1, "old");
            // Tạo đối tượng DefaultTableModel
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          
            model.addRow(new Object[]{nv.getTenTour(), nv.getMaTour(), nv.getLoaiTour(), nv.getTongsocho(), nv.getSochodu(), nv.getDiaDiemTour(), nv.getDiaDiemdi(), nv.getDiaDiemden(), nv.getSongaydi(), ngayDiString, ngayVeString, nv.getGiaTour()});

            // thêm đối tượng KhachHang vào model
// cập nhật lại model cho JTable
            jTable1.setModel(model);

// thông báo thành công
            JOptionPane.showMessageDialog(null, "Thêm Tour Thành Công");
            txtTenTour.setText("");
            txtMaTour.setText("");

            txtDiaDiemTour.setText("");
            txtDiaDiemDi.setText("");
            txtDiaDiemDen.setText("");
            txtSoNgayDi.setText("");
            txtSoChoDu.setText("");
            txtTongSoCho.setText("");
            txtSoNgayDi.setText("");
            txtGiaTour.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Nhập sai định dạng số");
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maNVCanTim = txtMaTour.getText();

        // Tạo một danh sách để lưu khách hàng tìm được
        ArrayList<Tour> ketQuaTimKiem = new ArrayList<>();

        // Lặp qua danh sách khách hàng hiện tại để tìm kiếm
        // Lặp qua danh sách khách hàng hiện tại để tìm kiếm
        for (Tour nv : danhSachTour) {
            if (nv.getMaTour().toLowerCase().contains(maNVCanTim.toLowerCase())) {
                ketQuaTimKiem.add(nv);
            }
        }

// Kiểm tra kết quả tìm kiếm
        if (ketQuaTimKiem.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kết Quả Không Tìm Thấy");
        } else {

        // Tạo một model mới để hiển thị kết quả tìm kiếm trên JTable
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tên Tour");
        model.addColumn("Mã Tour");
        model.addColumn("Loại Tour");
        model.addColumn("Tổng số chỗ");
        model.addColumn("Số chỗ dư");
        model.addColumn("Địa điểm Tour");
        model.addColumn("Địa điểm đi");
       model.addColumn("Địa điểm đến");
       model.addColumn("Số ngày đi");
       model.addColumn("Ngày đi");
       model.addColumn("Ngày về");
       model.addColumn("Giá Tour");

        // Thêm các khách hàng tìm được vào model
        for (Tour nv : ketQuaTimKiem) {
            model.addRow(new Object[]{nv.getTenTour(), nv.getMaTour(), nv.getLoaiTour(), nv.getTongsocho(), nv.getSochodu(), nv.getDiaDiemTour(), nv.getDiaDiemdi(), nv.getDiaDiemden(), nv.getSongaydi(), ngayDiString, ngayVeString, nv.getGiaTour()});
        }

        // Cập nhật lại model cho JTable
        jTable1.setModel(model);
    }       
    }//GEN-LAST:event_btnTimKiemActionPerformed
    private Date convertStringToDate(String dateString) {
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            return dateFormat.parse(dateString);
        } catch (ParseException ex) {
            return null;
        }
    }
    private void cbxNamVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNamVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNamVeActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // lấy chỉ số hàng được chọn trong JTable
        int selectedRow = jTable1.getSelectedRow();
        config con = new config();
        try {
            danhSachTour = con.layDL_Tour();
        } catch (SQLException ex) {
            Logger.getLogger(QlyTourDuLich.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
// nếu không có hàng nào được chọn, thông báo lỗi và kết thúc
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Một Hàng Để Xóa");
            return;
        }

// lấy ra model của JTable hiện tại
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// lấy mã khách hàng của hàng được chọn
        String maNV = (String) model.getValueAt(selectedRow, 1);

// tìm khách hàng trong danh sách dựa vào mã
        Tour tourCanXoa = null;
        for (Tour nv : danhSachTour) {
            if (nv.getMaTour().equals(maNV)) {
                tourCanXoa = nv;
                break;
            }
        }
        
// nếu không tìm thấy khách hàng, thông báo lỗi và kết thúc
        if (tourCanXoa == null) {
            JOptionPane.showMessageDialog(null, "Tour Không Tồn Tại");
            return;
        }

// xóa khách hàng khỏi danh sách
        danhSachTour.remove(tourCanXoa);
        con.UpdateSQL_Tour(tourCanXoa, 2, "null");
// xóa hàng được chọn trong model
        model.removeRow(selectedRow);

// cập nhật lại model cho JTable
        jTable1.setModel(model);

// thông báo thành công
        JOptionPane.showMessageDialog(null, "Xóa Tour Thành Công");

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
// lấy chỉ số hàng được chọn trong JTable
        int selectedRow = jTable1.getSelectedRow();
        
        config con = new config();
        try {
            danhSachTour = con.layDL_Tour();
        } catch (SQLException ex) {
            Logger.getLogger(QlyTourDuLich.class.getName()).log(Level.SEVERE, null, ex);
        }
// nếu không có hàng nào được chọn, thông báo lỗi và kết thúc
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui Lòng Chọn Một Hàng Để Sửa");
            return;
        }

// lấy ra model của JTable hiện tại
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// lấy mã khách hàng của hàng được chọn
        String maNV = (String) model.getValueAt(selectedRow, 1);
        String olDNV = maNV;
// tìm khách hàng trong danh sách dựa vào mã
        Tour tourCanSua = null;
        for (Tour nv : danhSachTour) {
            if (nv.getMaTour().equals(maNV)) {
                tourCanSua = nv;
                break;
            }
        }
        
// nếu không tìm thấy khách hàng, thông báo lỗi và kết thúc
        if (tourCanSua == null) {
            JOptionPane.showMessageDialog(null, "Tour Không Tồn Tại");
            return;
        }

// hiển thị form sửa thông tin khách hàng
        String tenTour = JOptionPane.showInputDialog(null, "Nhập tên Tour", tourCanSua.getTenTour());
        String maTour = JOptionPane.showInputDialog(null, "Nhập mã Tour", maNV);
        JComboBox<String> cbxLoaiTour = new JComboBox<>();
        cbxLoaiTour.addItem("Nhân Viên Bán Hàng");
        cbxLoaiTour.addItem("Quản Lý Kho");
        cbxLoaiTour.addItem("Nhân Viên Văn Phòng");
        cbxLoaiTour.setSelectedItem(tourCanSua.getLoaiTour());
        JOptionPane.showMessageDialog(null, cbxLoaiTour, "Chọn loại Tour", JOptionPane.QUESTION_MESSAGE);
        String loaiTour = (String) cbxLoaiTour.getSelectedItem();

        String tongSoCho = JOptionPane.showInputDialog(null, "Nhập tổng số chỗ", tourCanSua.getTongsocho());
        String soChoDu = JOptionPane.showInputDialog(null, "Nhập số chỗ dư", tourCanSua.getSochodu());
        String diaDiemTour = JOptionPane.showInputDialog(null, "Nhập địa điểm Tour", tourCanSua.getDiaDiemTour());
        String diaDiemDi = JOptionPane.showInputDialog(null, "Nhập địa điểm đi", tourCanSua.getDiaDiemdi());
        String diaDiemDen = JOptionPane.showInputDialog(null, "Nhập địa điểm đến", tourCanSua.getDiaDiemden());
        String soNgayDi = JOptionPane.showInputDialog(null, "Nhập số ngày đi", tourCanSua.getSongaydi());
// thêm ComboBox để chọn loại nhân viên
        JComboBox<String> cbxnamDi = new JComboBox<>();
        cbxnamDi.addItem("2023");

        cbxnamDi.setSelectedItem(tourCanSua.getNgaydi());

        JOptionPane.showMessageDialog(null, cbxnamDi, "Chọn năm đi", JOptionPane.QUESTION_MESSAGE);
        String namDiString = (String) cbxnamDi.getSelectedItem();
        int namDi = Integer.parseInt(namDiString);

        JComboBox<String> cbxThangDi = new JComboBox<>();
        int day = 0;
        for (int i = 1; i < 13; i++) {
            day = i;
            String Day = Integer.toString(day);
            cbxThangDi.addItem(Day);
            Day = "";
        }
        cbxThangDi.setSelectedItem(tourCanSua.getNgaydi());
        JOptionPane.showMessageDialog(null, cbxThangDi, "Chọn Tháng Đi", JOptionPane.QUESTION_MESSAGE);
        String TDiString = (String) cbxThangDi.getSelectedItem();
        int ThangDi = Integer.parseInt(TDiString);

        JComboBox<String> cbxNgayDi = new JComboBox<>();
        for (int i = 1; i < 32; i++) {
            String Day = Integer.toString(i);
            cbxNgayDi.addItem(Day);
            Day = "";
        }
        cbxNgayDi.setSelectedItem(tourCanSua.getNgaydi());
        JOptionPane.showMessageDialog(null, cbxNgayDi, "Chọn Ngày Đi", JOptionPane.QUESTION_MESSAGE);
        String ngaydi = (String) cbxNgayDi.getSelectedItem();
        int ngayDi = Integer.parseInt(ngaydi);

        JComboBox<String> cbxnamVe = new JComboBox<>();
        cbxnamVe.addItem("2023");

        cbxnamVe.setSelectedItem(tourCanSua.getNgaydi());

        JOptionPane.showMessageDialog(null, cbxnamVe, "Chọn năm về", JOptionPane.QUESTION_MESSAGE);
        String namVeString = (String) cbxnamDi.getSelectedItem();
        int namVe = Integer.parseInt(namVeString);
        JComboBox<String> cbxThangVe = new JComboBox<>();
        for (int i = 1; i < 13; i++) {
            day = i;
            String Day = Integer.toString(day);
            cbxThangVe.addItem(Day);
            Day = "";
        }
        cbxThangVe.setSelectedItem(tourCanSua.getNgaydi());
        JOptionPane.showMessageDialog(null, cbxThangVe, "Chọn Tháng Về", JOptionPane.QUESTION_MESSAGE);
        String TVeString = (String) cbxThangVe.getSelectedItem();
        int ThangVe = Integer.parseInt(TVeString);

        JComboBox<String> cbxNgayVe = new JComboBox<>();
        for (int i = 1; i < 32; i++) {
            String Day = Integer.toString(i);
            cbxNgayVe.addItem(Day);
            Day = "";
        }
        cbxNgayVe.setSelectedItem(tourCanSua.getNgaydi());
        JOptionPane.showMessageDialog(null, cbxNgayVe, "Chọn Ngày Về", JOptionPane.QUESTION_MESSAGE);
        String ngayve = (String) cbxNgayVe.getSelectedItem();
        int ngayVe = Integer.parseInt(ngayve);

        String giaTour = JOptionPane.showInputDialog(null, "Nhập Giá Tour", tourCanSua.getGiaTour());

        Calendar calendar = Calendar.getInstance();
            calendar.set(namDi , ThangDi, ngayDi);
            Date ngayDiDate = calendar.getTime();

            calendar.set(namVe , ThangVe, ngayVe);
            Date ngayVeDate = calendar.getTime();
           SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                String ngayDiString = dateFormat.format(ngayDiDate);
                String ngayVeString = dateFormat.format(ngayVeDate);
        
// cập nhật thông tin khách hàng
        tourCanSua.setTenTour(tenTour);
        tourCanSua.setMaTour(maTour);
        tourCanSua.setLoaiTour(loaiTour);
        int tongsocho = Integer.parseInt(tongSoCho);
        int sochodu = Integer.parseInt(soChoDu);
        tourCanSua.setTongsocho(tongsocho);
        tourCanSua.setSochodu(sochodu);
        tourCanSua.setDiaDiemTour(diaDiemTour);
        tourCanSua.setDiaDiemdi(diaDiemDi);
        tourCanSua.setDiaDiemden(diaDiemDen);
        int songaydi = Integer.parseInt(soNgayDi);
        tourCanSua.setSongaydi(songaydi);
        tourCanSua.setNgaydi(ngayDiDate);
        tourCanSua.setNgayve(ngayVeDate);
        long giatour = Long.parseLong(giaTour);
        tourCanSua.setGiaTour(giatour);
        
        
        con.UpdateSQL_Tour(tourCanSua,3,olDNV );
// cập nhật lại model cho JTable
        model.setValueAt(tenTour, selectedRow, 0);
        model.setValueAt(maTour, selectedRow, 1);
        model.setValueAt(loaiTour, selectedRow, 2);
        model.setValueAt(tongSoCho, selectedRow, 3);
        model.setValueAt(soChoDu, selectedRow, 4);
        model.setValueAt(diaDiemTour, selectedRow, 5);
        model.setValueAt(diaDiemDi, selectedRow, 6);
        model.setValueAt(diaDiemDen, selectedRow, 7);
        model.setValueAt(soNgayDi, selectedRow, 8);
        model.setValueAt(ngayDiString, selectedRow, 9);
        model.setValueAt(ngayVeString, selectedRow, 10);
        model.setValueAt(giaTour, selectedRow, 11);

// thông báo thành công
        JOptionPane.showMessageDialog(null, "Sửa Thông Tin Tour Thành Công");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void cbxLoaiTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiTourActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportActionPerformed

    private void txtDiaDiemDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaDiemDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaDiemDenActionPerformed
    private String ngayDiString;
    private String ngayVeString;
    private Date ngayDiDate;
    private Date ngayVeDate;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxLoaiTour;
    private javax.swing.JComboBox<String> cbxNamDi;
    private javax.swing.JComboBox<String> cbxNamVe;
    private javax.swing.JComboBox<String> cbxNgayDi;
    private javax.swing.JComboBox<String> cbxNgayVe;
    private javax.swing.JComboBox<String> cbxThangDi;
    private javax.swing.JComboBox<String> cbxThangVe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiaDiemDen;
    private javax.swing.JTextField txtDiaDiemDi;
    private javax.swing.JTextField txtDiaDiemTour;
    private javax.swing.JTextField txtGiaTour;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextField txtSoChoDu;
    private javax.swing.JTextField txtSoNgayDi;
    private javax.swing.JTextField txtTenTour;
    private javax.swing.JTextField txtTongSoCho;
    // End of variables declaration//GEN-END:variables

}
